#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SuperSwipeRefreshLayoutDemoApp.Resource", IsApplication=true)]

namespace SuperSwipeRefreshLayoutDemoApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int down_arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int file = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000f
			public const int ListViewButton = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int List_View = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int RecyclerViewButton = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int ScrollViewButton = 2131034128;
			
			// aapt resource value: 0x7f050004
			public const int Scroll_View = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int Swipe_Refresh = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int TextView = 2131034118;
			
			// aapt resource value: 0x7f050011
			public const int container = 2131034129;
			
			// aapt resource value: 0x7f05000a
			public const int footer_image_view = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int footer_pb_view = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int footer_text_view = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int head_container = 2131034119;
			
			// aapt resource value: 0x7f050012
			public const int image = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int image_view = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int linear_layout = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int pb_view = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int recycler_view = 2131034115;
			
			// aapt resource value: 0x7f050013
			public const int text = 2131034131;
			
			// aapt resource value: 0x7f05000b
			public const int text_view = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_ListView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Activity_RecyclerView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Activity_ScrollView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int layout_footer = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int layout_head = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RecyclerView_Item = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
